apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-catalog
  template:
    metadata:
      labels:
        app: notification-catalog
    spec:
      containers:
        - image: aljazv/notification-catalog:latest
          name: notification-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://snuffleupagus.db.elephantsql.com/ugawfgxl
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: ugawfgxl
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-catalog-database-password
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
            - name: KUMULUZEE_AMQP_RABBITMQ_HOSTS0_URL
              value: rabbitmq
          ports:
            - containerPort: 8080
              name: notif-port
              protocol: TCP
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: notification-catalog
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: notif-port
  selector:
    app: notification-catalog